### PR TITLE
RFC 1436 Compliant GOPHER Server

### PR DESCRIPTION
**Pull request by TravisWhitaker**
Provides an RFC 1436 compliant GOPHER server. With this API it would be trivial to build a general GOPHER/HTTP adapter with [servant-client](http://hackage.haskell.org/package/servant-client).

Uses Nix for the build.

Some TODO's:

- Add some nice `Response` builders that map Haskell types to GOPHER listings.
- Isomorphism between Servant API specifications and GOPHER APIs.
- Validate GOPHER requests so the caller doesn't need to.
- Write a client and use it to write tests.

I can't tell if I'm trolling or not...

### CODE REVIEW

**Comment by davidnuon** [comment]
Got it running using OmniWeb and cURL to access it! But I can't seem to get the server running outside of the GHCI. If I compile a standalone binary, it just halts.

Maybe I'm doing something wrong?

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Network.Gopher 

app :: GopherApp
app _ = let 
        k = Record
            { recName     = "Very Serious Things are coming"
            , recSelector = "AAAA"
            , recHost     = "localhost"
            , recPort     = 9001
            , recOther    = []
            }
    in
        pure $ Items [Listing PlainText k]

main = runGopherApp 9001 app
```



image

image

**Comment by TravisWhitaker** [comment]
A Haskell program will terminate when `main` returns, even if there are other threads running. The trick is to keep `main` from returning until the server's work is done, with something like this:

```haskell
main :: IO ()
main = do
    ... -- start some threads that do some work...
    catch (\UserInterrupt -> putStrLn "Going down now!") (forever (threadDelay 1000000))
```

Ideally this would also:
    - Catch additional signals, instead of just Ctrl-C.
    - Ask workers to shut down gracefully on exit instead of stopping abruptly, with a timeout.
    - Maybe do something useful instead of sleeping.

**Comment by TravisWhitaker** [comment]
See also the [async package](https://hackage.haskell.org/package/async), which provides a nice promise-like API for waiting on other threads in an exception-safe way.

**Comment by davidnuon** [comment]
Ah! That's really obvious now lol. Here's a screenshot of it working on Linux. I can't get the server to work in Windows but it works in Linux and macOS and that's good enough.

image

**Comment by davidnuon** [comment]
Also, which `catch` is that you're using? Can't seem to find a matching one on Hoogle.

**Comment by davidnuon** [comment]
Going to probably merge this in when I get home and turn the TODOs into issues. 👍

**Comment by TravisWhitaker** [comment]
I've got the args backwards in that example -.- It's [this guy](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#v:catch).

Hmm, this _should_ work on Windows. There might be something trying to be smart with `\r\n` <-> `\n`...

**Comment by davidnuon** [comment]
Re: Windows​: Maybe, I'll give it a look. If it doesn't work right away, I might just make it an issue.

**Comment by davidnuon** [comment]
Gonna merge this in and turn your TODOs into and Windows thing issues 👍

**Pull request merged**
